### ISSUE TITLE
Single quotes in argument breaks parsing

### ISSUE THREAD

**Issue by jamesbraza** [offscale/cdd-python#7]
The below code with Python 3.12 and `python-cdd==0.0.99rc47`:

```python
import cdd.docstring.parse

def my_function(arg: str) -> None:
    """Summary.

    Args:
        arg: A 'quoted' word. 
    """

cdd.docstring.parse.docstring(my_function.__doc__)
```

Will crash `_parse_adhoc_doc_for_typ_phase0` with `TypeError: unhashable type: 'list'`

```none
Traceback (most recent call last):
...
  File "/path/to/venv/lib/python3.12/site-packages/cdd/docstring/utils/parse_utils.py", line 263, in parse_adhoc_doc_for_typ
    candidate_type, fst_sentence, sentence = _parse_adhoc_doc_for_typ_phase0(doc, words)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/cdd/docstring/utils/parse_utils.py", line 410, in _parse_adhoc_doc_for_typ_phase0
    candidate_type: Optional[str] = next(
                                    ^^^^^
TypeError: unhashable type: 'list'
```

**Comment by SamuelMarks** [comment]
Thanks for the bug report, checking the `words` are:
```py
['A', ' ', [], '', '', ['q', 'u', 'o', 't', 'e', 'd'], 'quoted', '', ' ', 'word', '.']
```

Which is certainly not what we want at that stage.

In the middle of something let me see if I can resolve this issue in the next week. Thanks for using the library!

**Comment by SamuelMarks** [comment]
Good to have the bug report, checking the `words` are:
```py
['A', ' ', [], '', '', ['q', 'u', 'o', 't', 'e', 'd'], 'quoted', '', ' ', 'word', '.']
```

Which is certainly not what is wanted at this stage.

In the middle of something let me see if I can resolve this issue in the next week. Thanks for using the library!

**Comment by jamesbraza** [comment]
Yeah sounds good and thank you! I am trying to use this to go from type hinted signatures + docstrings to an OpenAPI spec

**Comment by SamuelMarks** [comment]
Good plan. The project is just about ready to do that reliably.

Anyway, will address the issue you brought up. Also have an uncommitted local build with some other improvements relating to type inference.
